select * from sales_data;

// age function 

select age(CURRENT_DATE,'12-2-1990')
from sales_data;

SELECT  TRANSACTION_DATE,AGE(CURRENT_DATE,TRANSACTION_DATE) AS DIFFRENCE
FROM SALES_DATA;
--1)UPPER FUNCTION
SELECT PRODUCT_NAME,UPPER(PRODUCT_NAME)
FROM SALES_DATA;

--2)LOWER FUNCTION
SELECT PRODUCT_NAME,LOWER(PRODUCT_NAME)
FROM SALES_DATA;

--3)LENGTH FUNCTION
SELECT PRODUCT_NAME,LENGTH(PRODUCT_NAME) 
FROM SALES_DATA;

--4) CONCAT FUNCTION
SELECT PRODUCT_NAME,PRODUCT_CATEGORY,CONCAT(PRODUCT_NAME,'/',PRODUCT_CATEGORY) AS PRODUCT_NAME_CATEGORY
FROM SALES_DATA;

--5)SUBSTRING FUNCTION
SELECT PRODUCT_NAME,SUBSTRING(PRODUCT_NAME,1,6)
FROM SALES_DATA;

--6)STRING POSITION FUNCTION
SELECT PRODUCT_NAME,STRPOS(PRODUCT_NAME,' ')+1
FROM SALES_DATA;

--7)GET SEPRATE FIRST NAME FROM CUSTROMER NAME
SELECT CUSTOMER_NAME,SUBSTRING(CUSTOMER_NAME,'1',STRPOS(CUSTOMER_NAME,' '))
FROM SALES_DATA;

--9)GET SEPRATE LAST NAME FROM CUSTROMER NAME
SELECT CUSTOMER_NAME,SUBSTRING(CUSTOMER_NAME,STRPOS(CUSTOMER_NAME,' ')+1,LENGTH(CUSTOMER_NAME)-STRPOS(CUSTOMER_NAME,' '))
FROM SALES_DATA;

--//INNER JOIN QUARY FOR TABLE 1
CREATE TABLE customers_data1 (
    Customer_ID VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(50),
    Age INT,
    City VARCHAR(30),
    Purchase_Amount DECIMAL(10,2)
);
select * from customers_data1;

--//INNER JOIN QUARY FOR TABLE 2
CREATE TABLE customers_data2 (
    Customer_ID VARCHAR(10),
    Product VARCHAR(50),
    Quantity INT,
    Purchase_Date DATE
);
SELECT * from CUSTOMERS_DATA2;

drop table customers_data1;

drop table customers_data2;

--1)//INNER JOIN QUERY-1
SELECT * 
FROM CUSTOMERS_DATA1 AS C1
INNER JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;

--2)//INNER JOIN QUARY-2
SELECT C1.PURCHASE_AMOUNT,C1.CITY,C2.PRODUCT
FROM CUSTOMERS_DATA1 AS C1
INNER JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;

--3)//LEFT JOIN QUARY-3

--4)//LEFT JOIN
SELECT * 
FROM CUSTOMERS_DATA1 AS C1
LEFT JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;


--2)//LEFT JOIN QUARY-2
SELECT C1.PURCHASE_AMOUNT,C1.CITY,C2.PRODUCT
FROM CUSTOMERS_DATA1 AS C1
INNER JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;

--3)//RIGHT OUTER JOIN
SELECT * 
FROM CUSTOMERS_DATA1 AS C1
RIGHT JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;


--4)//RIGHT OUTER  JOIN QUARY-2
SELECT C1.PURCHASE_AMOUNT,C1.CITY,C2.PRODUCT
FROM CUSTOMERS_DATA1 AS C1
RIGHT JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;

--5)//FULL OUTER  JOIN
SELECT * 
FROM CUSTOMERS_DATA1 AS C1
FULL OUTER JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;


--6)//FULL OUTER JOIN QUARY-2
SELECT C1.PURCHASE_AMOUNT,C1.CITY,C2.PRODUCT
FROM CUSTOMERS_DATA1 AS C1
FULL OUTER JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID;



--4)//JOIN WITH WHERE CLUASE
SELECT * 
FROM CUSTOMERS_DATA1 AS C1
LEFT JOIN CUSTOMERS_DATA2 AS C2
ON C1.CUSTOMER_ID=C1.CUSTOMER_ID
WHERE C1.CUSTOMER_ID IS NOT NULL;

--TABLE-1
--//UNION
--CREATING TABLE 
CREATE TABLE IF NOT EXISTS SALESMAN1
(
EMP_ID VARCHAR(20),
SALESMAN_NAME VARCHAR(50),
CITY VARCHAR(30)
);

SELECT * FROM SALESMAN1;

DROP TABLE SALESMAN1;

INSERT INTO SALESMAN1(EMP_ID,SALESMAN_NAME,CITY)
         VALUES ('E004','RAKUL','MUMBAI'),
		       ('E005','RAJ','KANPUR'),
			   ('E006','KHUSHI','UTTAR PRADESH'),
			   ('E007','RIYAJ','LUCKNOW');

--TABLE-2
CREATE TABLE IF NOT EXISTS SALESMAN2
(
EMP_ID VARCHAR(20),
SALESMAN_NAME VARCHAR(50),
CITY VARCHAR(30)
);

SELECT * FROM SALESMAN2;

DROP TABLE SALESMAN1;

INSERT INTO SALESMAN2(EMP_ID,SALESMAN_NAME,CITY)
         VALUES ('E001','RAKUL','MUMBAI'),
		       ('E002','RAJ','KANPUR'),
			   ('E003','KHUSHI','UTTAR PRADESH'),
			   ('E007','RIYAJ','LUCKNOW');			   
--UNION QUARY

SELECT * FROM SALESMAN1
UNION ALL
SELECT * FROM SALESMAN2;
			   